// <copyright file="ItemMetadata.cs" company="Oleg Sych">
//  Copyright © Oleg Sych. All Rights Reserved.
// </copyright>

namespace T4Toolbox
{
    /// <summary>
    /// Defines constants for commonly-used project item metadata.
    /// </summary>
    public static class ItemMetadata
    {
        /// <summary>
        /// Used by Visual Studio to store the "Copy to Output Directory" property.
        /// </summary>
        public const string CopyToOutputDirectory = "CopyToOutputDirectory";

        /// <summary>
        /// Used by Visual Studio to store the "Custom Tool Namespace" property.
        /// </summary>
        public const string CustomToolNamespace = "CustomToolNamespace";

        /// <summary>
        /// Used by Visual Studio to store the "Custom Tool" property.
        /// </summary>
        public const string Generator = "Generator";

        /// <summary>
        /// Used by Visual Studio to store name of the last file generated by an IVsSingleFileGenerator.
        /// </summary>
        public const string LastGenOutput = "LastGenOutput";

        /// <summary>
        /// Used by T4 Toolbox to store the list of files generated by transformation.
        /// </summary>
        public const string LastOutputs = "LastOutputs";

        /// <summary>
        /// Used by T4 Toolbox to store value of the "Custom Tool Template" property.
        /// </summary>
        public const string Template = "Template";
    }    
}